import os
from utils.colors import Colors
from utils.terminal_commands import run_command

def _ask_basic_info(question_text):
    print(f"\n{Colors.PURPLE}?{Colors.END} {Colors.BOLD}{question_text}{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")
    
    if input().lower().strip() == "y":
        user = input(f"  {Colors.DIM}↳{Colors.END} Username: ").strip() or "Your Name"
        mail = input(f"  {Colors.DIM}↳{Colors.END} Email: ").strip() or "you@example.com"
        return user, mail
    
    return "Your Name", "you@example.com"

def get_user_data():
    return _ask_basic_info("Configure pyproject.toml?")

def get_web_data():
    print(f"\n{Colors.PURPLE}?{Colors.END} {Colors.BOLD}Add your name to package.json?{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")
    if input().lower().strip() == "y":
        return input(f"  {Colors.DIM}↳{Colors.END} Username: ").strip() or "Your Name"
    return "Your Name"

def get_rust_data():
    user, email = _ask_basic_info("Add name and email to Cargo.toml?")
    license = input(f"  {Colors.DIM}↳{Colors.END} License: ").strip() or "MIT"
    return user, email, license

def get_readme_data(default_name):
    print(f"{Colors.PURPLE}?{Colors.END} {Colors.BOLD}Customize README?{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")
    if input().lower().strip() == "y":
        title = input(f"  {Colors.DIM}↳{Colors.END} Title [{default_name}]: ").strip() or default_name
        desc = input(f"  {Colors.DIM}↳{Colors.END} Description: ").strip() or "Project created with mkproj-cli."
        return title, desc
    return default_name, "Project created with mkproj-cli."

def get_module_go(default_name):
    print(f"\n{Colors.PURPLE}?{Colors.END} {Colors.BOLD}Use GitHub as Go module?{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")
    if input().lower().strip() == "y":
        repo = input(f"  {Colors.DIM}↳{Colors.END} Repo path (ex: github.com/user/repo): ").replace("https://", "").strip() or default_name
        return repo
    return default_name

def get_java_data():
    user = "user"
    print(f"\n{Colors.PURPLE}?{Colors.END} {Colors.BOLD}Developer/Org name or Domain?{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")
    if input().lower().strip() == "y":
        user = input(f"  {Colors.DIM}↳{Colors.END} Domain (ex: br.com.website): ").strip().lower() or "user"

    print(f"\n{Colors.PURPLE}?{Colors.END} {Colors.BOLD}Select Java template?{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")
    gui_choice = "1"
    if input().lower().strip() == "y":
        print(" 1) Console Application (Simple)")
        print(" 2) GUI Application (Swing/MVC)")
        gui_choice = input(f"  {Colors.DIM}↳{Colors.END} Selection (default: 1): ") or "1"
        
    return user, gui_choice

def git_automation(name):
    print(f"\n{Colors.PURPLE}?{Colors.END} {Colors.BOLD}Initialize Git repository?{Colors.END} {Colors.DIM}(y/n){Colors.END}", end=" ")

    if input().lower().strip() == "y":
        project_path = os.path.abspath(name)

        if run_command(["git", "init"], project_path):
            run_command(["git", "add", "."], project_path)
            run_command(["git", "commit", "-m", "chore: initial commit generated by mkproj-cli"], project_path)
            print(f"  {Colors.DIM}↳{Colors.END} {Colors.GREEN}Git initialized and first commit created!{Colors.END}")
        else:
            print(f"  {Colors.DIM}↳{Colors.END} {Colors.RED}Failed to initialize Git. Is it installed?{Colors.END}")